homeia/playground/views.py
#################
#### imports ####
#################

from flask import render_template, Blueprint, request, flash, redirect, url_for, Markup
import wiringpi2 as wiringpi 

################
#### config ####
################

WIRINGPI_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 14, 15, 16, 17]
wiringData = {
      'wiring_pin_list' : WIRINGPI_list,
      'wiring_pin_mode' : [0, 1],
      'wiring_pin_states' : [{'label' : 'Off', 'value' : 0}, {'label' : 'On', 'value' : 1}]
    }


playground_blueprint = Blueprint('playground', __name__)


################
#### routes ####
################

# use decorators to link the function to a url
@playground_blueprint.route('/')
def index():
    return render_template('playground/index.html', **wiringData)

@playground_blueprint.route('/wiring/<int:wp_id>/<int:wp_state>')
def wiring(wp_id, wp_state):
    wiringpi.wiringPiSetup()
    if wp_id in WIRINGPI_list:
        wiringpi.pinMode(wp_id, 1)
        wiringpi.digitalWrite(wp_id, wp_state)
        message = Markup(
            f'GPIO <strong>{str(wp_id)}</strong> switched to : {str(wp_state)}'
        )

        flash(message, 'success')
    else:
        flash('Invalid WiringPi number', 'danger')
    return render_template('playground/index.html', **wiringData)

@playground_blueprint.route('/i2c/<int:i2cAddr>/<i2cMode>/<int:i2cData>')
def i2c(i2cAddr, i2cMode, i2cData=None):

    # i2c = wiringpi2.I2C()
    # dev = i2c.setup(0x20) ( not sure about what to pass into the setup function, but presumably a device address? )
    # i2c.read(dev)

    i2c = wiringpi.I2C()
    dev = i2c.setup(0x20)

    i2cReturnedData = {
        'i2cAddress' : i2cAddr,
        #'i2cData' : i2c.read(dev)
        'i2cData' : 'returned data by I2C device'
    }

    message = Markup(
        f'I2C {str(i2cAddr)} returned : <strong>(not implemented yet)'
        + '</strong>'
    )

    flash(message, 'success')

    return render_template('playground/index.html', **i2cReturnedData)

homeia/templates/playground/_gpio.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Have fun with GPIO !</h3>
  </div>
  <div class="panel-body">
	<form role="form" class="form-inline">
		<div class="form-group">
			<select id="wiringPiPin" class="form-control">
			<option value="" selected disabled>WiringPi pin</option>
			{% for pin in wiring_pin_list %}
				<option value="{{ pin }}">{{ pin }}</option>
			{% endfor %}
			</select>
		</div>
		<div class="form-group">
			<select id="wiringPiState" class="form-control">
			<option value="" selected disabled>Outpute state</option>
			{% for state in wiring_pin_states %}
				<option value="{{ state.value }}">{{ state.label }}</option>
			{% endfor %}
			</select>
		</div>
		<input type="button" name="go" value="Go!" class="btn btn-primary" onClick="digitalWrite()">

		<script type="text/javascript">
		
		function digitalWrite()
		{
			var wiringPiPin = document.getElementById("wiringPiPin").value;
		  	var wiringPiState = document.getElementById("wiringPiState").value;
			if ( wiringPiPin && wiringPiState ){
		  		window.location='{{ url_for('playground.index') }}wiring/'+ wiringPiPin +'/'+ wiringPiState;
			}
			else {
				alert('wrong parameters');
			}
		}

		// jQuery style
		/*
		    $(function(){
		      // bind change event to select
		      $('#dynamic_select').bind('change', function () {
		          var url = $(this).val(); // get selected value
		          if (url) { // require a URL
		              window.location = url; // redirect
		          }
		          return false;
		      });
		    });
		*/

		</script>
	</form>
  </div>
 </div>

homeia/templates/playground/_i2c.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Have fun with I2C !</h3>
  </div>
  <div class="panel-body">
	<form role="form" class="form-inline">
		<div class="form-group">
			<input type="text" id="I2CDeviceAddress" class="form-control" placeholder="Enter I2C Address">
		</div>
		<div class="form-group">
			<select id="I2CMode" class="form-control">
			<option value="" selected disabled>Mode (R/W)</option>
				<option value="read">Read</option>
				<option value="read">Write</option>
			</select>
		</div>
		<input type="button" name="go" value="Go!" class="btn btn-primary" onClick="I2CAction()">

		<script type="text/javascript">
		
		function I2CAction()
		{
			var I2CDeviceAddress = document.getElementById("I2CDeviceAddress").value;
		  	var I2CMode = document.getElementById("I2CMode").value;
			if ( I2CDeviceAddress && I2CDeviceAddress ){
		  		window.location='{{ url_for('playground.index') }}i2c/'+ I2CDeviceAddress +'/'+ I2CMode + '/';
			}
			else {
				alert('wrong parameters');
			}
		}

		// jQuery style
		/*
		    $(function(){
		      // bind change event to select
		      $('#dynamic_select').bind('change', function () {
		          var url = $(this).val(); // get selected value
		          if (url) { // require a URL
		              window.location = url; // redirect
		          }
		          return false;
		      });
		    });
		*/

		</script>
	</form>
  </div>
 </div>

homeia/templates/playground/_pinsstates.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Pins states </h3>
  </div>
  <div class="panel-body">
    <table class="table table-condensed table-bordered table-striped">
    	<tr><th>WiringPi pin</th><th>GPIO</th><th>Name</th><th>Header P1</th><th>Header P1</th><th>Name</th><th>GPIO</th><th>WiringPi pin</th></tr>
    	<tbody>
    		<tr><td></td><td></td><td>3V3</td><td>1</td><td>2</td><td>5V</td><td></td><td></td></tr>
    		<tr><td>8</td><td>Rv1:0 - Rv2:2</td><td>SDA</td><td>3</td><td>4</td><td>5V</td><td></td><td></td></tr>
    		<tr><td>9</td><td>Rv1:1 - Rv2:3</td><td>SCL</td><td>5</td><td>6</td><td>0V</td><td></td><td></td></tr>
    		<tr><td>7</td><td>4</td><td>GPIO7</td><td>7</td><td>8</td><td>TxD</td><td>14</td><td>15</td></tr>
    		<tr><td></td><td></td><td>0V</td><td>9</td><td>10</td><td>RxD</td><td>15</td><td>16</td></tr>
    		<tr><td>0</td><td>17</td><td>GPIO0</td><td>11</td><td>12</td><td>GPIO1</td><td>18</td><td>1</td></tr>
    		<tr><td>2</td><td>Rv1:0 - Rv2:2</td><td>GPIO2</td><td>13</td><td>14</td><td>0V</td><td></td><td></td></tr>
    		<tr><td>3</td><td>22</td><td>GPIO3</td><td>15</td><td>16</td><td>GPIO4</td><td>23</td><td>4</td></tr>
    		<tr><td></td><td></td><td>3.3V</td><td>17</td><td>18</td><td>GPIO5</td><td>24</td><td>5</td></tr>
    		<tr><td>12</td><td>10</td><td>MOSI</td><td>19</td><td>20</td><td>0V</td><td></td><td></td></tr>
    		<tr><td>13</td><td>9</td><td>MISO</td><td>21</td><td>22</td><td>GPIO6</td><td>25</td><td>6</td></tr>
    		<tr><td>14</td><td>11</td><td>SCLK</td><td>23</td><td>24</td><td>CE0</td><td>8</td><td>10</td></tr>
    		<tr><td></td><td></td><td>OV</td><td>25</td><td>26</td><td>CE1</td><td>7</td><td>11</td></tr>
    	</tbody>
    </table>
  </div>
</div>

homeia/templates/playground/_serial.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Serial terminal</h3>
  </div>
  <div class="panel-body">
    console
  </div>
</div>

homeia/templates/playground/index.html
{% extends "layouts/layout-2columns.html" %}
{% set active_page = "overview" %}
{% block body %}
<h1 class="page-header">Playground</h1>
<div class="row">
	<div class="col-md-4">
		{% include '/playground/_gpio.html' %}
	</div>
	<div class="col-md-8">
		{% include '/playground/_i2c.html' %}
	</div>
</div>
{% include '/playground/_pinsstates.html' %}
{% include '/playground/_serial.html' %}

{% endblock %}