homeia/system/views.py
#################
#### imports ####
#################

from flask import render_template, Blueprint, request, flash, redirect, url_for
import os

################
#### config ####
################

system_blueprint = Blueprint('system', __name__)

from homeia.system.models import System

################
#### routes ####
################

# use decorators to link the function to a url

@system_blueprint.route('/system/reboot')
def reboot():
    #print u.deleteportmapping(app.config['WEBPORT'], 'TCP')
    flash('System is rebooting', 'warning')
    os.system("sudo shutdown -r now")
    return redirect(url_for('dashboard.index'))

@system_blueprint.route('/system/shutdown')
def shutdown():
    #print u.deleteportmapping(app.config['WEBPORT'], 'TCP')
    flash('System is shuting down', 'warning')
    os.system("sudo shutdown -h now")
    return redirect(url_for('dashboard.index'))

@system_blueprint.route('/system/stop')
def stop():
    #print u.deleteportmapping(app.config['WEBPORT'], 'TCP')
    System.shutdown_server()
    return 'Server shutting down...'

homeia/templates/layouts/_head.html
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>HOMEIA Dashboard</title>

  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/dashboard.css') }}">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    <script type=text/javascript>
      $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
    </head>

homeia/templates/layouts/_navbar.html
{% set navigation_navbar = [
    ('dashboard.index', 'Dashboard'),
    ('settings.index', 'Settings')
] -%}
<div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('dashboard.index') }}">HOMEIA</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% for id, caption in navigation_navbar %}
              <li{% if id == active_page %} class="active"{% endif
              %}><a href="{{ url_for(id)|e }}">{{ caption|e }}</a></li>
            {% endfor %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Profile <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="">Sign in</a></li>
                <li><a href="">Sign up</a></li>
                <li><a href="">Sign out</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">System <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a onclick="return confirm('Confirm reboot')" href="{{ url_for('system.reboot') }}">Reboot</a></li>
                <li><a onclick="return confirm('Confirm shutdown')" href="{{ url_for('system.shutdown') }}">Shut down</a></li>
                <li role="presentation" class="divider"></li>
                <li><a onclick="return confirm('Confirm shutdown homeia server')" href="{{ url_for('system.stop') }}">stop server</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>

homeia/templates/layouts/_sidebar.html
{% set navigation_sidebar = [
    ('dashboard.index', 'Overview'),
    ('playground.index', 'Playground')
] -%}
		<h3>sidebar</h3>
          <ul class="nav nav-sidebar">
            {% for id, caption in navigation_sidebar %}
              <li{% if id == active_page %} class="active"{% endif
              %}><a href="{{ url_for(id)|e }}">{{ caption|e }}</a></li>
            {% endfor %}
          </ul>
          <!-- futur categories -->
          <!-- <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul> -->

homeia/templates/layouts/layout-2columns.html
{% set active_page = active_page|default('index') -%}
<!DOCTYPE html>
<html lang="en">
  {% include 'layouts/_head.html' %}
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      {% include 'layouts/_navbar.html' %}
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% include 'layouts/_sidebar.html' %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <!-- {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
          {% endfor %}
          {% endif %}
          {% endwith %} -->
          {% block body %}{% endblock %}
        </div>
      </div>
    </div>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
     <!-- <script src="{{ url_for('static', filename='js/sysinfos.js') }}"></script> -->
  </body>
    </html>

homeia/templates/layouts/layout-single.html
{% set active_page = active_page|default('index') -%}
<!DOCTYPE html>
<html lang="en">
    {% include 'layouts/_head.html' %}
    <body>

      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        {% include 'layouts/_navbar.html' %}
      </nav>

      <div class="container-fluid">
        <div class="main">
          <!-- {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
          {% endfor %}
          {% endif %}
          {% endwith %} -->
          {% block body %}{% endblock %}
        </div>
      </div>
      <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
       <!-- <script src="{{ url_for('static', filename='js/sysinfos.js') }}"></script> -->
    </body>
    </html>